const MIN_POSITIVE_NUMBER = 0;
const COUNT_OF_MOCKS = 10;

const MIN_ELEMENTS = 1;

const MIN_LOCATION_X = 35.65;
const MAX_LOCATION_X = 35.7;
const MIN_LOCATION_Y = 139.7;
const MAX_LOCATION_Y = 139.8;

const MIN_PRICE = {
  flat: 1000,
  bungalow: 0,
  house: 5000,
  palace: 10000,
};
const MAX_PRICE = 1000000;

const MAX_COUNT_OF_AVATARS = 8;
const MAX_COUNT_OF_DECIMAL_NUMBERS = 5;
const MAX_FEATURES = 6;
const MAX_PHOTOS = 3;

export {
  MIN_ELEMENTS, MIN_POSITIVE_NUMBER, COUNT_OF_MOCKS, MIN_LOCATION_X, MIN_LOCATION_Y,
  MAX_LOCATION_X, MAX_LOCATION_Y, MAX_PRICE, MAX_COUNT_OF_AVATARS, MAX_COUNT_OF_DECIMAL_NUMBERS,
  MAX_FEATURES, MAX_PHOTOS, MIN_PRICE
};
