const MIN_POSITIVE_NUMBER = 0;
const COUNT_OF_PINS = 10;

const MIN_ELEMENT = 1;

const MIN_LOCATION_X = 35.65;
const MAX_LOCATION_X = 35.7;
const MIN_LOCATION_Y = 139.7;
const MAX_LOCATION_Y = 139.8;

const MIN_PRICE = {
  flat: 1000,
  bungalow: 0,
  house: 5000,
  palace: 10000,
};
const MAX_PRICE = 1000000;

const MAX_COUNT_OF_AVATARS = 8;
const MAX_COUNT_OF_DECIMAL_NUMBERS = 5;
const MAX_FEATURES = 6;
const MAX_PHOTOS = 3;

const TOKYO_LATITUDE = 35.6895;
const TOKYO_LONGITUDE = 139.69171;
const MAIN_PIN = 52;
const PIN = 40;
const START_POINTS = `${TOKYO_LATITUDE}, ${TOKYO_LONGITUDE}`;
const START_POINTS_OBJECT = {
  lat: TOKYO_LATITUDE,
  lng: TOKYO_LONGITUDE,
};

const ERROR_MESSAGE = 'Не удалось отправить форму. Попробуйте ещё раз';

export {
  MIN_ELEMENT, MIN_POSITIVE_NUMBER, COUNT_OF_PINS, MIN_LOCATION_X, MIN_LOCATION_Y,
  MAX_LOCATION_X, MAX_LOCATION_Y, MAX_PRICE, MAX_COUNT_OF_AVATARS, MAX_COUNT_OF_DECIMAL_NUMBERS,
  MAX_FEATURES, MAX_PHOTOS, MIN_PRICE, TOKYO_LATITUDE, TOKYO_LONGITUDE, MAIN_PIN, PIN, START_POINTS,
  START_POINTS_OBJECT, ERROR_MESSAGE
};
